org: domchevska
app: bartender
service: api-dynamodb-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  environment:    
    DYNAMODB_TABLE:
      "Fn::ImportValue": "cocktails-serverless-table-${self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/cocktails-serverless-table-${self:provider.stage}"

plugins:
  - serverless-bundle

functions:
  getAllCocktails:
    handler: build/api-dynamodb-service/src/getAllCocktails.getAllCocktails
    events:
      - http:
          path: cocktails/all
          method: get
  getCocktailByName:
    handler: build/api-dynamodb-service/src/getCocktailByName.getCocktailByName
    events:
      - http:
          path: cocktails
          method: get
  saveCocktail:
    handler: build/api-dynamodb-service/src/saveCocktail.saveCocktail
    events:
      - http:
          path: cocktails
          method: post