org: domchevska
app: bartender
service: s3-sqs-service
frameworkVersion: '2'

custom:
  bucket: olena-domchevska-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  environment:
    QUEUE_URL: { Ref: S3Queue }
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:*:*:S3Queue"
functions:
  process-s3-to-sqs:
    handler: ../../build/processS3Bucket.main
    events:
        - s3: ${self:custom.bucket}
resources:
      Resources:
        S3Queue: 
          Type: "AWS::SQS::Queue"
          Properties: 
            QueueName: "S3Queue"