service: s3-sqs-service
frameworkVersion: "2"

custom:
  bucket: olena-domchevska-s3-bucket

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
  tracing:
    lambda: true

  environment:
    QUEUE_URL:
      "Fn::ImportValue": "cocktails-serverless-queue-${self:provider.stage}"
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
      Resource: arn:aws:sqs:*:*:cocktails-serverless-queue-${self:provider.stage}

plugins:
  - serverless-bundle

functions:
  processS3Bucket:
    handler: build/s3-sqs-service/src/processS3Bucket.s3processor
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json