service: sqs-dynamodb-lambda
frameworkVersion: "2"

custom:
  sqs_arn: arn:aws:sqs:${opt:region, self:provider.region}:530260462866:cocktails-serverless-queue-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
  tracing:
    lambda: true
  environment:
    DYNAMODB_TABLE:
      "Fn::ImportValue": "cocktails-serverless-table-${self:provider.stage}"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/cocktails-serverless-table-${self:provider.stage}"
    - Effect: Allow
      Action:
        - "sqs:*"
      Resource: arn:aws:sqs:${opt:region, self:provider.region}:*:cocktails-serverless-queue-${self:provider.stage}

plugins:
  - serverless-bundle

functions:
  processSqsMessage:
    handler: build/sqs-dynamodb-service/src/processSqsMessage.processSqsMessage
    events:
      - sqs:
          arn: ${self:custom.sqs_arn}
          batchSize: 1
